name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PLATFORMS: linux/arm64
  SOURCE_REPOSITORY: freeCodeCamp/devdocs
  DOCKERHUB_REPOSITORY: helllord/devdocs

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Fetch get_tag.py
        uses: actions/checkout@v4
        with:
          repository: hellbot77/get-tag
          sparse-checkout: get_tag.py
          sparse-checkout-cone-mode: false
      - name: Get Docker image tag
        id: get-tag
        run: >
          python3 get_tag.py ${{ github.event_name != 'workflow_dispatch' && env.DOCKERHUB_REPOSITORY || '""' }}
          --gh-commit ${{ env.SOURCE_REPOSITORY }} >> $GITHUB_OUTPUT

  build-push:
    needs: get-tag
    if: ${{ needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          ref: ${{ needs.get-tag.outputs.tag }}
      - name: Apply patch
        run: |
          if [[ "$(head -n 1 Dockerfile)" == "FROM ruby:3.3.0" ]]; then
            PATCH="
            FROM debian:bookworm as base
            RUN apt update && apt install -y build-essential wget autoconf
            RUN wget https://github.com/postmodern/ruby-install/releases/download/v0.9.3/ruby-install-0.9.3.tar.gz \
              && tar -xzvf ruby-install-0.9.3.tar.gz \
              && cd ruby-install-0.9.3/ \
              && make install
            RUN ruby-install -p https://github.com/ruby/ruby/pull/9371.diff ruby 3.3.0
            ENV PATH=\"/opt/rubies/ruby-3.3.0/bin:\${PATH}\"
            "
            echo -e "$PATCH$(tail -n +2 Dockerfile)" > Dockerfile
          fi
      - name: Set Docker Hub username
        id: dockerhub-username
        run: echo "username=${DOCKERHUB_REPOSITORY%%/*}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.dockerhub-username.outputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ needs.get-tag.outputs.tag }}
            ${{ env.DOCKERHUB_REPOSITORY }}:latest

  cancel-action:
    needs: get-tag
    if: ${{ !needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel action
        uses: andymckay/cancel-action@0.3
      - name: Wait for cancel
        run: sleep infinity
